MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: 'swin_tiny_patch4_window7_224_22kto1k_finetune.pth' #swin_base_patch4_window7_224_22kto1k.pth
 # PRETRAIN_PATH: 'resnet50-19c8e357.pth'
  METRIC_LOSS_TYPE: 'triplet' #'triplet_center'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no' #'no'
  # TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  NO_MARGIN: True
  DEVICE_ID: ('0')
  NECK: 'bnneck'
  NAME: 'swinTransformer'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5   # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:

  NAMES: ('market1501') #dukemtmc
  ROOT_DIR: data

DATALOADER:
  SAMPLER: 'softmax_triplet'

  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'


  MAX_EPOCHS:  120


  BASE_LR: 0.00035   #0.00035
  LARGE_FC_LR: False
  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY:  0.0001 # 0.0005
  WEIGHT_DECAY_BIAS: 0.0001
  IMS_PER_BATCH: 64


  STEPS: [40,70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 20
  EVAL_PERIOD: 40

TEST:
  IMS_PER_BATCH: 128 #128
  RE_RANKING: 'no' #'no'
  WEIGHT: "path"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "output/market1501/swin"


